spin_manifest_version = 2

[application]
name = "challenge-1"
version = "0.1.0"
authors = ["Thorsten Hans <thorsten.hans@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "frontend"

[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "frontend", destination = "/" }]

[[trigger.http]]
route = "/data"
component = "wishlist"

[component.wishlist]
source = "wishlist/target/wasm32-wasi/release/wishlist.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]

[component.wishlist.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "wishlist"
watch = ["src/**/*.rs", "Cargo.toml"]
