spin_manifest_version = 2

[application]
name = "challenge-4"
version = "0.1.0"
authors = ["Thorsten Hans <thorsten.hans@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "api"

[component.api]
source = "api/target/wasm32-wasi/release/api.wasm"
allowed_outbound_hosts = []
[component.api.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "api"
watch = ["src/**/*.rs", "Cargo.toml"]
